import type { Metadata } from "next";
import {SocketProvider}from "../context/SocketProvider"
import { AuthProvider } from "./AuthProvider";

export const metadata: Metadata = {
  title: "Connectly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <SocketProvider>
          <body>
            {children}
          </body>
        </SocketProvider>
      </AuthProvider>
    </html>
  );
}
